"""交付物打包——.zip 归档（v0.9）。

参考 HM-Pro ``dossier.py`` 的 ``build_dossier()`` 模式：把论文 PDF + LaTeX
源 + 代码 + 依赖表 + 图表打包成一个自包含的 .zip。

HM-Pro 用 .zip（非 tar.gz），HAA 沿用。
"""

from __future__ import annotations

import logging
import zipfile
from pathlib import Path

logger = logging.getLogger("haa.p3.packager")


def package_deliverable(
    paper_dir: str | Path,
    output_path: str | Path,
    *,
    code_dir: str | Path | None = None,
    results_dir: str | Path | None = None,
    project_title: str = "HAA Paper",
) -> Path:
    """打包交付物为 .zip。

    包含：
    - ``paper/`` — LaTeX 源（main.tex, sections/*.tex, refs.bib, math_commands.tex）
    - ``paper/main.pdf`` — 编译后的 PDF（如有）
    - ``code/`` — 实验代码（如有）
    - ``results/`` — 实验结果 JSON/CSV/图表（如有）
    - ``MANIFEST.md`` — 内容清单

    Returns .zip 文件路径。
    """
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    paper_dir = Path(paper_dir)

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        # Paper source.
        if paper_dir.exists():
            for f in paper_dir.rglob("*"):
                if f.is_file() and f.suffix not in (".aux", ".log", ".blg", ".out", ".fls"):
                    arcname = f"paper/{f.relative_to(paper_dir)}"
                    zf.write(f, arcname)

        # Code.
        if code_dir and Path(code_dir).exists():
            for f in Path(code_dir).rglob("*"):
                if f.is_file() and f.name not in (".gitignore",):
                    if "__pycache__" in f.parts or ".git" in f.parts:
                        continue
                    arcname = f"code/{f.relative_to(code_dir)}"
                    zf.write(f, arcname)

        # Results.
        if results_dir and Path(results_dir).exists():
            for f in Path(results_dir).rglob("*"):
                if f.is_file():
                    arcname = f"results/{f.relative_to(results_dir)}"
                    zf.write(f, arcname)

        # Manifest.
        manifest = _build_manifest(paper_dir, code_dir, results_dir, project_title)
        zf.writestr("MANIFEST.md", manifest)

    logger.info("deliverable packaged: %s (%d bytes)", output, output.stat().st_size)
    return output


def _build_manifest(
    paper_dir: Path | None,
    code_dir: str | Path | None,
    results_dir: str | Path | None,
    title: str,
) -> str:
    """生成 MANIFEST.md 内容清单。"""
    lines = [
        f"# {title}",
        "",
        "## Contents",
        "",
        "- `paper/` — LaTeX source (main.tex + sections/*.tex + refs.bib)",
    ]
    paper_dir = Path(paper_dir) if paper_dir else None
    if paper_dir and (paper_dir / "main.pdf").exists():
        lines.append("- `paper/main.pdf` — compiled PDF")
    if code_dir and Path(code_dir).exists():
        lines.append("- `code/` — experiment code")
    if results_dir and Path(results_dir).exists():
        lines.append("- `results/` — experiment results (metrics, figures)")

    lines += [
        "",
        "## How to compile",
        "",
        "```bash",
        "cd paper",
        "pdflatex main.tex && bibtex main && pdflatex main.tex && pdflatex main.tex",
        "```",
        "",
        "---",
        "Generated by HAA (Hyacinth Automated Analyzer)",
    ]
    return "\n".join(lines) + "\n"
